### ISSUE TITLE
TypeError for getwindowlist()

### ISSUE THREAD

**Issue by Zitrax** [ldtp/cobra#10]
I got this in 4.0.0 when calling getwindowlist(), the call worked after commenting out that logger call.

```
>>> from ldtp import *
>>> getwindowlist()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 71, in
__call__
    for k, v in kwargs.items()])))
TypeError: unsupported operand type(s) for +: 'map' and 'list'
```

**Comment by nagappan** [comment]
Whats your python version ?

**Comment by Zitrax** [comment]
3.4.3

**Comment by Zitrax** [comment]
Another issue I am seeing is a window that is listed when calling `getwindowlist()` but when I am calling `getobjectlist()` on that I get `xmlrpc.client.Fault: <Fault 123: 'Unable to find window: frm[foo] bar'>`. Might be something different just thought I should mention it here if it's my setup that is not correct.

**Comment by nagappan** [comment]
I haven't tested with 3.x in Windows, will be happy to integrate a patch which will work both on 3.x and 2.x python. I guess probably the window title have regexp string

**Comment by Zitrax** [comment]
About the window; it indeed seem to be a problem with those brackets in the title, replacing that part with a * and it works.

**Comment by Zitrax** [comment]
Added patch.

Btw, maybe wrong place to ask - but I have noticed that `getwindowlist()` is quite slow - average of around 8 seconds on my machine, is that expected ?

**Comment by Zitrax** [comment]
About the slowness, I noticed that Qt Creator was opened in the background and it started to use 100% CPU as soon as some ldtp test ran. Closing that caused my tests to run 6 times faster.

**Comment by nagappan** [comment]
Interesting, I haven't played with QT app on Windows, good to know. Thanks

**Comment by joshery420** [comment]
Sorry to bring up an old issue, but I'm still having this exact problem.
Is the fix from @Zitrax's patch available in the latest binaries or no?

Both Python 3.3.5 and 3.4.3 have this problem in my testing, whereas 2.7.10 does not. Also, to be sure I tested 32-bit and 64-bit versions of each Python version, and only the two 2.7.10 installs worked.
Platform is Windows 7 64-bit.

**Comment by Zitrax** [comment]
The latest binary release seem to be from 2013 so no. Would be nice with a new release.

I have been building from source to get the latest changes.

**Comment by joshery420** [comment]
Gotcha. I suppose I could try to figure that out if I need to, but a binary with the Python 3 friendly changes would be much nicer. @nagappan, any chance of getting an updated 4.0.1 binary or something?
