### ISSUE TITLE
Can't read text from QTextBrowser

### ISSUE THREAD

**Issue by Zitrax** [ldtp/cobra#15]
In a Qt app if there is a QTextBrowser element it's detected as a label by ldtp, it has type `ControlType.Text`.

However if I try to call `ldtp.gettextvalue('window', 'lbl0')` I get _"Unable to find object: lbl0"_ since `Text.cs` does not include `ControlType.Text`among it's candidates in `Text::GetObjectHandle()`. I added it there and recompiled and then I got the text value that I needed.

I am unsure if that is the proper fix though, should this type have been detected as something else ? 

But otherwise it's a simple fix that solves my problem.

**Comment by nagappan** [comment]
You are right, not sure how I missed that, can you please send a review ? Thanks
