### ISSUE TITLE
Help with build and package instructions?

### ISSUE THREAD

**Issue by joshsleeper** [ldtp/cobra#25]
I'm trying to build cobra from source to see if I can get improved Python 3 support (the latest official release, 4.0.0, doesn't auto-start the service like it does with Python 2.7) but having some trouble following the provided instructions.

I've downloaded Visual Studio 2015 CE and built the `SetEnvironmentVariable` and `CobraWinLdtp` solutions, but I'm not sure where to go next. The build and package instructions simply say

> ... place the binary where you have all the dll's, README.txt, License.rtf, before running Wix installer commands.

but I'm not sure which binary (I'm guessing it might be referring to `"..\CobraWinLdtp\bin\Debug\CobraWinLdtp.exe"` that I just built?)
I'm also unsure what or where "all the dll's" are, or if I'm supposed to move `README.txt` and `License.rtf`, or copy things into where they are.

If you can guide my hand a bit here I'd be happy to submit a PR to clean up the existing instructions.
Also for the record I'm using Visual Studio 2015 CE on Windows 10 Professional 64-bit.

Thanks!

**Comment by nagappan** [comment]
It's been quite a while I built these packages and my hard drive went down during a power outage and haven't set it back. After March 15, let me redo things, it's been long pending.

Place the cobrawinldtp.exe under CobraWinLDTP folder (https://github.com/ldtp/cobra/tree/master/CobraWinLDTP). I have no prior build experience, just got instructions from one of my colleague and did it :-)

**Comment by joshery420** [comment]
Sounds great @nagappan, I'll give that a shot for now.
So you think we can expect an updated release in March then, hopefully? :+1:

**Comment by Zitrax** [comment]
When I worked with this last I added the `build_installer.bat` file which you can find in the root to make it easier for me. You might want to give that a try.

**Comment by joshery420** [comment]
Silly me, I remember reading that you'd added that, but totally forgot about it when I was attempting the build myself. -_-
I'll give that a try, thanks @Zitrax!

**Comment by joshery420** [comment]
Hey @nagappan, just checking in to see if you still had intent to release an updated LDTP build sometime soon. :)
