### ISSUE TITLE
Python bindings missing common functions?

### ISSUE THREAD

**Issue by joshsleeper** [ldtp/cobra#26]
A number of methods I use in Python don't show up as autocomplete suggestions, and I think it's because they're not present in the **init**.py bindings.
For example, click(), selectrowindex(), and mousemove() are all absent.

Is this intentional, or would submitting a PR to add some more methods be useful?
Also, suggestions about how I might determine what methods should and shouldn't be added if I wanted to do that?

**Comment by nagappan** [comment]
I always use the tab filling, not sure why you are not seeing it. Right now have access only to Mac environment.

>>> from atomac import ldtp
>>> ldtp.
Display all 211 possibilities? (y or n) 

When I tried tab I see above message.

**Comment by joshery420** [comment]
Autocomplete in both PyCharm 5.0.4 and Visual Studio Code 10.10 refuse to show me more than a subset of methods available.

For example, given the following code:
```python
import ldtp
ldtp.click()
```

When typing, PyCharm doesn't suggest click() as a valid method, and after typing it manually it gives me a warning when hovering over click() that reads:
> Cannot find reference 'click' in '\_\_init\_\_.py' less... (Ctrl+F1) 
> This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.

If it matters, I'm using Python 2.7.10 on Windows 7 64-bit

**Comment by nagappan** [comment]
Interesting, I never tried from editor. Not sure, how to fix it. Will be happy to integrate the patch if available.

**Comment by joshery420** [comment]
The obvious answer seems to be doing what PyCharm suggests I suppose, which is having the full set of API hooks listed in \_\_init\_\_.py, although I'm not confident whether that's the actual problem or just an easy solution. Also, Visual Studio Code I'd be more willing to ignore issues with, but it's strange seeing that issue with PyCharm, a full-fledged Python IDE. 

So you're getting full autocomplete with atomacs (which looks like either an emacs package for Atom, or a fork of Atom that's more emacs like) even though methods like click() aren't listed in your root \_\_init\_\_.py?

**Comment by rrzaripov** [comment]
@joshery420 the part of ldtp methods is getting during runtime, from client, and adds they to the global namespace. Look at `_populateNamespace method` in `__init__.py`. I think this is cause of the lacking autocomplete in PyCharm. Yes, hardcode methods definition in `__init__.py` solve this problem, but this is not good solution.
By the way, this [feature](http://blog.jetbrains.com/pycharm/2013/02/dynamic-runtime-type-inference-in-pycharm-2-7/) not work for our purpose (or I'm not use it in right way). Another ability is use [skeletons](https://www.jetbrains.com/pycharm/help/using-python-skeletons.html) for PyCharm. But I hope to find IDE-independent solution, as for example patch for ldtp.
